version: '3'

vars:
  EXEC_FILE: './cmd/booklib'
  OUTPUT: './bin/booklib/main'
  POSTGRES_URI: 'postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST/$POSTGRES_DB_NAME'

dotenv: ['.env']

tasks:
  build:
    cmd: go build -o {{.OUTPUT}} {{.EXEC_FILE}}
    silent: true

  run:
    deps:
      - task: build
    cmd: '{{.OUTPUT}}'
    silent: true

  db:
    cmd: docker compose up db -d

  docker-stop:
    aliases: [ds]
    cmd: docker compose stop

  db-connect:
    aliases: [dbc]
    cmd: psql "{{.POSTGRES_URI}}"

  migration:
    aliases: [mg]
    cmds:
      - 'goose postgres {{.POSTGRES_URI}} {{.CLI_ARGS}} -dir={{.WD}}'
    vars:
      WD: '{{.USER_WORKING_DIR}}/migrations'
    silent: true
  
  tidy:
    aliases: [td]
    cmd: go mod tidy
